"""empty message

Revision ID: 3abaf631426c
Revises: 51e2c29ad95
Create Date: 2019-09-15 05:09:36.342716

"""

# revision identifiers, used by Alembic.
revision = '3abaf631426c'
down_revision = '51e2c29ad95'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Artist',
    sa.Column('fullname', sa.String(length=200), nullable=False),
    sa.Column('artist_handle', sa.String(length=50), nullable=False),
    sa.Column('dob', sa.String(length=30), nullable=False),
    sa.Column('genre', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=20), nullable=False),
    sa.Column('date_joined', sa.DateTime(), nullable=True),
    sa.Column('donations_total', sa.String(length=500), nullable=True),
    sa.Column('follower_count', sa.Integer(), nullable=False),
    sa.Column('following_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('fullname', 'artist_handle', 'dob', 'genre', 'username', 'password', 'follower_count', 'following_count'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Artist')
    # ### end Alembic commands ###
