"""empty message

Revision ID: 6f2b20d88276
Revises: 3abaf631426c
Create Date: 2019-09-15 05:11:57.066414

"""

# revision identifiers, used by Alembic.
revision = '6f2b20d88276'
down_revision = '3abaf631426c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
