"""empty message

Revision ID: 819745e99ff1
Revises: b544f029b900
Create Date: 2019-09-15 12:34:47.686648

"""

# revision identifiers, used by Alembic.
revision = '819745e99ff1'
down_revision = 'b544f029b900'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
