"""empty message

Revision ID: b544f029b900
Revises: 6f2b20d88276
Create Date: 2019-09-15 12:28:40.860749

"""

# revision identifiers, used by Alembic.
revision = 'b544f029b900'
down_revision = '6f2b20d88276'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Album',
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('album_id', sa.Integer(), nullable=False),
    sa.Column('genre', sa.String(length=50), nullable=False),
    sa.Column('album_release_date', sa.DateTime(), nullable=True),
    sa.Column('length', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('title', 'album_id', 'genre', 'length')
    )
    op.add_column('Artist', sa.Column('artist_id', sa.Integer(), nullable=False))
    op.add_column('Artist', sa.Column('user_active', sa.Boolean(), nullable=False))
    op.create_unique_constraint(None, 'Artist', ['artist_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Artist', type_='unique')
    op.drop_column('Artist', 'user_active')
    op.drop_column('Artist', 'artist_id')
    op.drop_table('Album')
    # ### end Alembic commands ###
